web: 
  image: nginx:alpine
  ports: 
    - "8081:8080"
  volumes:
    - .:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php: 
  image: php:fpm-alpine
  volumes:
    - .:/code
